export const GET_CIRCLES = 'GET_CIRCLES';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_UNIVERSITIES = 'FETCH_UNIVERSITIES';
export const FETCH_TYPES = 'FETCH_TYPES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_SUBCATEGORIES = 'FETCH_SUBCATEGORIES';
