export const GET_CIRCLES = 'GET_CIRCLES';
export const FETCH_PUBLIC_CIRCLE = 'FETCH_PUBLIC_CIRCLE';
export const REMOVE_PUBLIC_CIRCLE = 'REMOVE_PUBLIC_CIRCLE';
export const FETCH_ACTIVE_CIRCLE = 'FETCH_ACTIVE_CIRCLE';
export const REMOVE_ACTIVE_CIRCLE = 'REMOVE_ACTIVE_CIRCLE';

export const CHANGE_LOGO = 'CHANGE_LOGO';
export const CHANGE_BACKGROUND = 'CHANGE_BACKGROUND';
export const CHANGE_CARD_DATA = 'CHANGE_CARD_DATA';
export const CHANGE_SOCIALS = 'CHANGE_SOCIALS';
export const CHANGE_COLORS = 'CHANGE_COLORS';
export const CHANGE_TAGS = 'CHANGE_TAGS';
export const REORDER_MODULES = 'REORDER_MODULES';

export const ADD_MODULE = 'ADD_MODULE';
export const UPDATE_MODULE = 'UPDATE_MODULE';
export const DELETE_MODULE = 'DELETE_MODULE';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';
export const UPDATE_QUERY = 'UPDATE_QUERY';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
