export const GET_CIRCLES = 'GET_CIRCLES';
export const FETCH_PUBLIC_CIRCLE = 'FETCH_PUBLIC_CIRCLE';

export const FETCH_ACTIVE_CIRCLE = 'FETCH_ACTIVE_CIRCLE';
export const CHANGE_LOGO = 'CHANGE_LOGO';
export const CHANGE_CARD_DATA = 'CHANGE_CARD_DATA';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
